import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { createI18n } from "vue-i18n";

const savedLanguage = localStorage.getItem("userLanguage") || "pl";

const i18n = createI18n({
  legacy: false,
  locale: savedLanguage,
  messages: {
    en: {
      noteCreated: "Created on",
      edit: "Edit",
      delete: "Delete",
      backToList: "← Back to list",
      error: "An error occurred",
      deletedNotesHistory: "Deleted Notes History",
      deletedOn: "Deleted on",
      noDeletedNotes: "No deleted notes.",
      deletedNote: "Deleted Note",
      backToHistory: "← Back to history",
      userNotes: "Your Notes",
      noNotes: "No notes. Add a new note!",
      addNote: "Add note",
      register: "Register",
      login: "Login",
      password: "Password",
      repeatPassword: "Repeat Password",
      usernameExists: "Username already exists.",
      passwordMismatch: "Passwords do not match! Please try again.",
      fieldsRequired: "Please fill in all fields.",
      registrationSuccess: "Registration successful!",
      notebook: "Notebook.php",
      notes: "notes",
      history: "notes history",
      logout: "Logout",
      loginError: "Incorrect login or password. Please try again.",
      missingFields: "Please fill in all fields.",
      welcome: "Welcome to the notebook",
      loggedIn:
        "👋 Welcome, you're logged in! You can now use all the features.",
      notLoggedIn: "🔑 You're not logged in. Please",
      loginLink: "Log in",
      notebookDescription:
        "The notebook is an application that allows you to save notes. You can save, edit, delete, and view notes—all easily and enjoyably.",
      loginRequired:
        "To use the notebook, you need to log in. If you don't have an account, you can create one by clicking the appropriate option in the navigation menu.",
      copyright: "Notebook © 2025",
      authors: "Authors",
      author1: "Jakub Kuźnicki",
      author2: "Dawid Mańkowski",
      editNote: "Edit Note",
      noteTitle: "Note Title",
      noteContent: "Note Content",
      saveChanges: "Save Changes",
      success: "Note updated successfully!",
      addNewNote: "Add a New Note",
      loginPlaceholder: "np. John",
      passwordPlaceholder: "Enter password",
      repeatPasswordPlaceholder: "Repeat password",
      noteTitlePlaceholder: "Enter note title",
      noteContentPlaceholder: "Enter note content",
    },
    pl: {
      noteCreated: "Utworzono",
      edit: "Edytuj",
      delete: "Usuń",
      backToList: "← Powrót do listy",
      error: "Wystąpił błąd",
      deletedNotesHistory: "Historia usuniętych notatek",
      deletedOn: "Usunięto",
      noDeletedNotes: "Brak usuniętych notatek.",
      deletedNote: "Usunięta notatka",
      backToHistory: "← Powrót do historii",
      userNotes: "Twoje notatki",
      noNotes: "Brak notatek. Dodaj nową notatkę!",
      addNote: "Dodaj notatkę",
      register: "Rejestracja",
      login: "Logowanie",
      password: "Hasło",
      repeatPassword: "Powtórz hasło",
      usernameExists: "Użytkownik o takim loginie już istnieje.",
      passwordMismatch: "Hasła się nie zgadzają! Proszę spróbować ponownie.",
      fieldsRequired: "Proszę wypełnić wszystkie pola.",
      registrationSuccess: "Rejestracja zakończona sukcesem!",
      notebook: "Notatnik.php",
      notes: "notatki",
      history: "historia notatek",
      logout: "Wyloguj",
      loginError: "Błędny login lub hasło. Proszę spróbować ponownie.",
      missingFields: "Proszę wypełnić wszystkie pola.",
      welcome: "Witaj w notatniku",
      loggedIn:
        "👋 Witaj, jesteś zalogowany! Możesz korzystać z dodatkowych funkcji.",
      notLoggedIn: "🔑 Nie jesteś zalogowany.",
      loginLink: "Zaloguj się",
      notebookDescription:
        "Notatnik to aplikacja, która pozwala na zapisywanie notatek. Możesz zapisywać, edytować, usuwać i przeglądać notatki w łatwy sposób.",
      loginRequired:
        "Aby korzystać z notatnika, musisz się zalogować. Jeśli nie masz konta, załóż je, klikając odpowiednią opcję w menu.",
      copyright: "Notatnik © 2025",
      authors: "Autorzy",
      author1: "Jakub Kuźnicki",
      author2: "Dawid Mańkowski",
      editNote: "Edytuj notatkę",
      noteTitle: "Tytuł notatki",
      noteContent: "Treść notatki",
      saveChanges: "Zapisz zmiany",
      success: "Notatka została zaktualizowana pomyślnie!",
      addNewNote: "Dodaj nową notatkę",
      loginPlaceholder: "np. Mariusz",
      passwordPlaceholder: "Wprowadź hasło",
      repeatPasswordPlaceholder: "Powtórz hasło",
      noteTitlePlaceholder: "Wprowadź tytuł notatki",
      noteContentPlaceholder: "Wprowadź treść notatki",
    },
  },
});

createApp(App).use(i18n).use(router).mount("#app");
